name: CI/CD with Docker
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v4
      - name: Docker Buildxをセットアップ
        uses: docker/setup-buildx-action@v3
      - name: Dockerメタデータを生成
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            mura0914/centos-nginx
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=raw,value=latest
      - name: DockerHubにログイン
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Dockerイメージをビルド、プッシュ
        uses: docker/build-push-action@v6
        with:
          context: docker/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: サーバーにSSHしてDockerコンテナをデプロイ
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port:${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/centos-nginx:latest
            docker stop my-nginx-container || true
            docker rm my-nginx-container || true
            docker run -d --name my-nginx-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/centos-nginx:latest
